name: chordly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^5.4.0
  provider: ^6.1.1
  share_plus: ^10.1.3
  cloud_firestore: ^5.6.1
  pdf: ^3.10.3
  path_provider: ^2.0.11
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
