name: chordly
description: A new Flutter project for managing songs and playlists in groups.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  google_sign_in: ^6.2.1

  # Estado y DI
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  
  # Utilidades
  intl: ^0.18.1
  uuid: ^4.3.3
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.2
  permission_handler: ^11.2.1
  pdf: ^3.10.7
  printing: ^5.11.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  color_dark: "#121212"
  image_dark: assets/images/splash_dark.png
  android_12:
    image: assets/images/splash_android12.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/splash_android12_dark.png
    icon_background_color_dark: "#121212"
